name:                word-processor
version:             0.1.0.0
github:              "anniechen18/word-processor"
license:             BSD3
author:              "Annie Chen"
maintainer:          "annie@mercury.com"
copyright:           "2022 Annie Chen"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/anniechen18/word-processor#readme>

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs: src

executables:
  word-processor-exe:
    main:                StringBufEditor.hs 
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - word-processor

tests:
  word-processor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - word-processor
